# Generated by Django 4.0.2 on 2022-03-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_added',
        ),
    ]
