# Generated by Django 4.0.2 on 2022-03-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0004_documentlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentList',
        ),
    ]
