# Generated by Django 4.0.2 on 2022-03-03 17:13

import DocumentManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=DocumentManagement.models.user_directory_path),
        ),
    ]
